name: deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64 \
          -t juandev3918/api_sorteos:1.0 \
          --push .
      - name: Trigger render webhook deploy
        run: |
          curl -X POST "${{ secrets.RENDER_WEBHOOOK_DEPLOY_URL}}"
